### ISSUE TITLE
Modèle de calcul "chauffer mon appart avec mes ampoules"

### ISSUE THREAD

**Issue by laem** [laem/futureco-data#129]
```yaml

DPE logement: 69 kWh/m2
DPE logement . chauffage: (2.5 / 4.3) * DPE logement

besoin énergétique: DPE logement . chauffage * 63 m2
besoin de puissance moyenne . kW: 
  formule: besoin énergétique / heures de chauffe
besoin de puissance moyenne: 
  formule: kW * 1000
  unité: W
heures de chauffe: 
  formule: 4 * 30 * 24
  unité: kWh / kW
  description: mois de chauffe * jours par mois * heures par jour

part des ampoules:  fourni par les ampoules / besoin de puissance moyenne

fourni par les ampoules: 
  formule: ampoules

ampoules:
  somme: 
    - salle de bain
    - entrée
    - chambre
    - bureau 
    - salon
    - toilettes

chambre: 9 W
bureau: 9 W
entrée: 2 * 9 W
salle de bain: 2 * 10 W + 9 W
salon: 15 W + 18 W + 9 W + 5 * 10 W

toilettes:
  valeur: 0
  description: |
    Pas possible de laisser toilettes et salle de bain ouverte
    
```
